# Lab 4

# Bias vs variance with subgroups

# generate some data

# lets have 4 groups, <+25, 25-50, 51-75, >75
# lets say they have probability of adverse reaction of 
p1 <- .04 
p2 <- .07 
p3 <- .13 
p4 <- .24

s1 <- 10
s2 <- 50
s3 <- 30
s4 <- 45

n=10000

set.seed(3)
data <- data.frame('group1' = rbinom(n, s1, p1)/s1,
                   'group2' = rbinom(n, s2, p2)/s2,
                   'group3' = rbinom(n, s3, p3)/s3,
                   'group4' = rbinom(n, s4, p4)/s4)
p <- c(p1, p2, p3, p4)
s <- c(s1, s2, s3, s4)
p # true prop
apply(data, 2, mean) #  mean sample prop
apply(data, 2, var) #  variances of sample prop

# combine groups so have <=50 and >50
data_combined <- data.frame((data['group1']*s1 + data['group2']*s2)/(s1+s2),
                            (data['group3']*s3 + data['group4']*s4)/(s3+s4))
colnames(data_combined) <- c("<=50", ">50")

p_comb <- c((p1*s1 + p2*s2)/(s1+s2), (p3*s3 + p4*s4)/(s3+s4))
s_comb <- c(s1 + s2, s3 + s4)
p_comb # true prop
apply(data_combined, 2, mean) #  mean sample prop
apply(data_combined, 2, var) # variances of sample prop

# Compare variances and proportions. Which grouping is better for each of these?

# Challenge: 
# Create an Rmarkdown file
# generate a data frame with one variable called binomial generated by a bimon(4, .3) 
# and two variables called normal1, normal2 generated by norm(13, 2.3) and norm(2, 7.1)
# create a scatter plot of normal1 and normal2 
# Describe the graph
# generate a pdf that shows the graph and your description, but not the code
# If you've done all that, go head and look at summary statistics
# if you consider the variables binomial as a grouping, how do the groups differ (if at all)?